-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 17:48:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveidor` (
  `id_proveidor` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(10) NOT NULL,
  `telefon` INT NOT NULL,
  `fax` INT ZEROFILL NULL,
  `correu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_proveidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `idmarca` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `proveidor_id` INT NOT NULL,
  PRIMARY KEY (`idmarca`, `proveidor_id`),
  INDEX `fk_marca_Proveidor1_idx` (`proveidor_id` ASC) VISIBLE,
  CONSTRAINT `fk_marca_Proveidor1`
    FOREIGN KEY (`proveidor_id`)
    REFERENCES `mydb`.`proveidor` (`id_proveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ulleres` (
  `id_ulleres` INT NOT NULL,
  `graduacio_dreta` DECIMAL NOT NULL,
  `graduacio_esquerre` DECIMAL NOT NULL,
  `montura` ENUM('pasta', 'flotant', 'metàl·lica') NOT NULL,
  `color_vidre_dret` ENUM('gris', 'verd', 'marró', 'groc', 'taronja', 'SC') NOT NULL,
  `Color_vidre_esquerre` ENUM('gris', 'verd', 'marró', 'groc', 'taronja', 'SC') NOT NULL,
  `preu` DECIMAL(2) NOT NULL,
  `marca_id` INT NOT NULL,
  PRIMARY KEY (`id_ulleres`, `marca_id`),
  INDEX `fk_Ulleres_marca1_idx` (`marca_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ulleres_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `mydb`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `cognom1` VARCHAR(45) NULL,
  `cognom2` VARCHAR(45) NULL,
  `direccio` VARCHAR(45) NULL,
  `telefon` INT NOT NULL,
  `correu` VARCHAR(45) NULL,
  `alta_registre` DATE NOT NULL,
  `recomanat` INT ZEROFILL NULL,
  CONSTRAINT `Recomanat`
    FOREIGN KEY (`idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleats` (
  `idEmpleats` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `cognom` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleats`),
  UNIQUE INDEX `idEmpleats_UNIQUE` (`idEmpleats` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nova_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nova_compra` (
  `id_client` INT NOT NULL,
  `id_empleat` INT NOT NULL,
  `data_registre` DATE NOT NULL,
  `Ulleres_idUlleres` INT NOT NULL,
  PRIMARY KEY (`id_client`, `Ulleres_idUlleres`, `id_empleat`),
  INDEX `idEmpleats_idx` (`id_empleat` ASC) VISIBLE,
  INDEX `ulleres_id_idx` (`Ulleres_idUlleres` ASC) VISIBLE,
  CONSTRAINT `id_Client`
    FOREIGN KEY (`id_client`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idEmpleats`
    FOREIGN KEY (`id_empleat`)
    REFERENCES `mydb`.`Empleats` (`idEmpleats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ulleres_id`
    FOREIGN KEY (`Ulleres_idUlleres`)
    REFERENCES `mydb`.`ulleres` (`id_ulleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`direccio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direccio` (
  `proveidor_id` INT UNSIGNED NOT NULL,
  `carrer` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(6) NOT NULL,
  `pis` VARCHAR(3) NOT NULL,
  `porta` VARCHAR(2) NULL,
  `ciutat` TEXT(10) NULL,
  `codi_postal` VARCHAR(10) NOT NULL,
  `pais` TEXT(45) NOT NULL,
  PRIMARY KEY (`proveidor_id`),
  CONSTRAINT `fk_Direccio_Proveidor1`
    FOREIGN KEY (`proveidor_id`)
    REFERENCES `mydb`.`proveidor` (`id_proveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
