-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 19:06:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(10) NOT NULL,
  `cognoms` VARCHAR(20) NOT NULL,
  `direccio` VARCHAR(45) NOT NULL,
  `localitat` VARCHAR(45) NULL,
  `CP` INT(5) NOT NULL,
  `provincia` TEXT(20) NULL,
  `telefon` INT(9) NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`botiga` (
  `idBotiga` INT NOT NULL AUTO_INCREMENT,
  `direccio` VARCHAR(45) NOT NULL,
  `CP` INT(5) NOT NULL,
  `localitat` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBotiga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`treballador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`treballador` (
  `idTreballador` INT NOT NULL AUTO_INCREMENT,
  `lloc_treball` ENUM('cuiner', 'repartidor') NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `cognoms` VARCHAR(45) NULL,
  `NIF` VARCHAR(9) NOT NULL,
  `telefon` INT(9) NOT NULL,
  `botiga_id` INT NOT NULL,
  PRIMARY KEY (`idTreballador`),
  INDEX `idBotiga_idx` (`botiga_id` ASC) VISIBLE,
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE,
  CONSTRAINT `idBotiga`
    FOREIGN KEY (`botiga_id`)
    REFERENCES `pizzeria`.`botiga` (`idBotiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`entrega_domicili`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`entrega_domicili` (
  `idEntrega` INT NOT NULL AUTO_INCREMENT,
  `registre_data` DATETIME NOT NULL,
  `treballador_id` INT NOT NULL,
  PRIMARY KEY (`idEntrega`),
  INDEX `fk_Entrega_domicili_Treballador1_idx` (`treballador_id` ASC) VISIBLE,
  CONSTRAINT `fk_Entrega_domicili_Treballador1`
    FOREIGN KEY (`treballador_id`)
    REFERENCES `pizzeria`.`treballador` (`idTreballador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comanda` (
  `idComanda` INT NOT NULL AUTO_INCREMENT,
  `entrega` ENUM('Botiga', 'Domicili') NOT NULL,
  `preu_total` FLOAT NOT NULL,
  `registre_data` DATE NOT NULL,
  `client_id` INT NOT NULL,
  `treballador_id` INT NOT NULL,
  `entrega_domicili_id` INT NOT NULL,
  `botiga_id` INT NOT NULL,
  PRIMARY KEY (`idComanda`),
  INDEX `idClient_idx` (`client_id` ASC) VISIBLE,
  UNIQUE INDEX `idNova_comanda_UNIQUE` (`idComanda` ASC) VISIBLE,
  UNIQUE INDEX `id_client_UNIQUE` (`client_id` ASC) VISIBLE,
  INDEX `fk_comanda_Treballador1_idx` (`treballador_id` ASC) VISIBLE,
  INDEX `fk_comanda_entrega_domicili1_idx` (`entrega_domicili_id` ASC) VISIBLE,
  INDEX `fk_comanda_Botiga1_idx` (`botiga_id` ASC) VISIBLE,
  CONSTRAINT `idClient`
    FOREIGN KEY (`client_id`)
    REFERENCES `pizzeria`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_Treballador1`
    FOREIGN KEY (`treballador_id`)
    REFERENCES `pizzeria`.`treballador` (`idTreballador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_entrega_domicili1`
    FOREIGN KEY (`entrega_domicili_id`)
    REFERENCES `pizzeria`.`entrega_domicili` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_Botiga1`
    FOREIGN KEY (`botiga_id`)
    REFERENCES `pizzeria`.`botiga` (`idBotiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`categoria` (
  `idCategoria` INT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`productes` (
  `idProducte` INT NOT NULL AUTO_INCREMENT,
  `tipus` ENUM('pizza', 'hamburguesa', 'begudes') NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` VARCHAR(60) NOT NULL,
  `imatge` BLOB NULL,
  `preu` FLOAT NULL,
  `categoria_id` INT NULL,
  PRIMARY KEY (`idProducte`),
  INDEX `idCategoria_idx` (`categoria_id` ASC) VISIBLE,
  UNIQUE INDEX `id_producte_UNIQUE` (`idProducte` ASC) VISIBLE,
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `pizzeria`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`comanda_productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comanda_productes` (
  `producte_id` INT NOT NULL,
  `comanda_id` INT NOT NULL,
  `quantitat` INT(2) NULL,
  INDEX `id_producte_idx` (`producte_id` ASC) VISIBLE,
  PRIMARY KEY (`producte_id`, `comanda_id`),
  INDEX `fk_comanda_productes_comanda1_idx` (`comanda_id` ASC) VISIBLE,
  CONSTRAINT `id_producte`
    FOREIGN KEY (`producte_id`)
    REFERENCES `pizzeria`.`productes` (`idProducte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_productes_comanda1`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `pizzeria`.`comanda` (`idComanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
